format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/apps/spack/1.1/release/linux-x86_64/access3-2025.08.000-byixk7ikxefmnqjxskrh2nvujmjhat4h/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: fda27d4110d2e48cdb6615861c39db93
    md5: 5523ef7dc89cce8c07693c9606caa4a0
